### ISSUE TITLE
Script fails with several errors… gnutls, python-install-directory, abbrev-file

### ISSUE THREAD

**Issue by sptankard** [AndreaCrotti/minimal-emacs-configuration#2]
Looks like a great script. 

Unfortunately, it doesn't seem to be working for me. It fails with several errors. Any ideas for how I might get this working? I have a pretty default setup, so I imagine it might be failing for quite a few people in a similar way.

This is the output of my `*Messages*` buffer:
```
For information about GNU Emacs and the GNU system, type C-h C-a.
Importing package-keyring.gpg...done
Contacting host: melpa.milkbox.net:80 [2 times]
Contacting host: elpa.gnu.org:80
Contacting host: marmalade-repo.org:80
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.
Don't see where py-install-directory is set, see README.org, taking default-directory: ~/.emacs.d/minimal-emacs-configuration/
Warning: no abbrev-file found, customize `abbrev-file-name' in order to make mode-specific abbrevs work. 
You should have a section marked ";;; Commentary:"

The first line should be of the form: ";;; package --- Summary"
You should have a section marked ";;; Commentary:"

The first line should be of the form: ";;; package --- Summary"
```

I am on Fedora 21, using GNU Emacs 24.4.1 from the fedora-updates repo.
```
Name        : emacs
Arch        : x86_64
Epoch       : 1
Version     : 24.4
Release     : 3.fc21
Size        : 14 M
Repo        : installed
From repo   : updates
```

**Comment by baztian** [comment]
I think you can simply ignore the error and warning messages. I get the same output. But it really works. Try to edit a python file to see if you really have problems.

**Comment by AndreaCrotti** [comment]
Ah yes I forgot to reply to this, it's a known Emacs issue but it still works anyway, so don't worry about that @sptankard

**Comment by sptankard** [comment]
Perhaps it works if you already have el-get/melpa installed?  

Sadly, I never did get this script to work for me (I did try editing python files, and there were no new features over plain emacs), but instead I got the desired functionality by installing [prelude] (https://github.com/bbatsov/prelude).
